model:
  class_path: source.paropt_model.ParoptModel
  init_args:
    name: 'paropt'
    rec_batch_size: 5000  # half memory
    k: 10000
    out_channels: 7
    workers: 8

data:
  init_args:
    batch_size: 8  # 16 GB GPU memory
    workers: 8

data:
  class_path: source.paropt_data_loader.ParoptDataModule

trainer:
  max_epochs: 500
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: './models'
